'use strict';
const $=id=>document.getElementById(id),token=document.querySelector('meta[name="editor-token"]').content;
let session='',overview=null,tab='overview',employeeId=1,page=0,query='',changes={},baseline={},labels={},inventoryData=null,itemDetails={},overviewLevelCache=[];
let inventorySource='',inventoryKind='',inventorySort='source';let renderGeneration=0;let employeePresetHistory=[];const employeePresetOptions=new Map();
const clone=x=>JSON.parse(JSON.stringify(x)),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function button(text,fn,cls=''){const e=el('button',text,cls);e.onclick=run(fn);return e;}
function run(fn){return async()=>{try{await fn();}catch(e){status(e.message,true);}};}
function status(s,error=false){$('status').textContent=s;$('status').className=error?'error':'';}
async function api(path,data){const r=await fetch(path,{method:data===undefined?'GET':'POST',headers:{'X-Editor-Token':token,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d;}
async function poll(job){for(;;){const s=await api('/api/status?job='+job);if(s.state==='done')return s.result;if(s.state==='error')throw Error(s.error);await new Promise(r=>setTimeout(r,600));}}
const base=()=>'?job='+session;
async function view(section){return api('/api/view'+base()+'&section='+section+'&id='+employeeId+'&page='+page+'&q='+encodeURIComponent(query));}
function remember(path,v,label=path){if(!(path in baseline))baseline[path]=clone(v);labels[path]=label;}
function value(path,original){return path in changes?changes[path]:original;}
function pending(){const n=Object.keys(changes).length;$('pending').textContent=n?`已暂存 ${n} 项修改`:'尚无修改';$('review').disabled=!n;}
function change(path,next){
 const m=path.match(/^(\/Items|\/Charas\/\d+\/Attr\/SkillSDatas)\/(\d+)\/(\w+)$/);
 if(m&&m[1] in changes){const a=clone(changes[m[1]]);a[Number(m[2])][m[3]]=next;return change(m[1],a);}
 if(same(baseline[path],next))delete changes[path];else changes[path]=clone(next);
 if(Array.isArray(next))for(const key of Object.keys(changes))if(key.startsWith(path+'/'))delete changes[key];
 pending();
}
function appliedArray(path,original){const a=clone(value(path,original));for(const [p,v] of Object.entries(changes)){const s=p.startsWith(path+'/')?p.slice(path.length+1).split('/'):[];if(s.length===2&&a[Number(s[0])])a[Number(s[0])][s[1]]=v;}return a;}
function textvalue(v){return typeof v==='string'?v:JSON.stringify(v);}
function displayNumber(v){return typeof v==='number'&&!Number.isInteger(v)?Number(v.toFixed(4)):v;}
function fieldControl(f){
 const parent=f.path.match(/^(\/Items|\/Charas\/\d+\/Attr\/SkillSDatas)\//);
 if(parent&&parent[1] in changes)f={...f,rule:null};
 remember(f.path,f.value,f.label+' · '+f.path);const wrap=el('label',undefined,'field');wrap.append(el('span',f.label),el('small',f.path));
 if(!f.rule){wrap.append(el('div',textvalue(f.value),'readonly'));return wrap;}
 const spec=f.rule;let input;
 if(spec.choices){input=el('select');for(const o of spec.choices){const opt=el('option',o.label);opt.value=String(o.value);input.append(opt);}input.value=String(value(f.path,f.value));}
 else{input=el('input');input.type=spec.type==='string'?'text':'number';const original=value(f.path,f.value);input.value=input.type==='number'?displayNumber(original):original;input.title='完整值：'+original;if(input.type==='number'){input.required=true;input.min=spec.min;input.max=spec.max;input.step=spec.type==='integer'?'1':'any';}else input.maxLength=spec.max;}
 input.dataset.path=f.path;input.setAttribute('aria-label',f.label);
 input.addEventListener(spec.choices?'change':'input',()=>{const v=spec.type==='string'||spec.type==='choice'?input.value:Number(input.value);change(f.path,v);if(f.path==='/ShopLevel'){const exp=document.querySelector('input[data-path="/ShopExp"]'),lv=overviewLevelCache.find(x=>x.level===v);if(exp&&lv)exp.max=Math.max(0,lv.next_exp-1);}wrap.classList.toggle('changed',f.path in changes);});
 wrap.classList.toggle('changed',f.path in changes);wrap.append(input);if(spec.help)wrap.append(el('small',spec.help));return wrap;
}
function fieldsGrid(fields){const grid=el('div',undefined,'fieldgrid');for(const f of fields)if(f)grid.append(fieldControl(f));return grid;}
function title(text,help){$('content').append(el('h2',text));if(help)$('content').append(el('p',help));}
function table(headers){const wrap=el('div',undefined,'tablewrap'),t=el('table'),head=el('thead'),tr=el('tr'),body=el('tbody');for(const h of headers)tr.append(el('th',h));head.append(tr);t.append(head,body);wrap.append(t);$('content').append(wrap);return body;}
function row(body,values){const tr=el('tr');for(const v of values){const td=el('td');if(v instanceof Node)td.append(v);else td.textContent=v==null?'—':String(v);tr.append(td);}body.append(tr);}
function pager(count,size,redraw){const line=el('div',undefined,'line'),prev=button('上一页',async()=>{page--;await redraw();},'secondary'),next=button('下一页',async()=>{page++;await redraw();},'secondary');prev.disabled=page===0;next.disabled=(page+1)*size>=count;line.append(prev,el('span',`第 ${page+1} / ${Math.max(1,Math.ceil(count/size))} 页 · ${count} 项`),next);$('content').append(line);}
function searchbar(redraw,placeholder='按中文名称或 ID 搜索'){const line=el('div',undefined,'line'),input=el('input');input.value=query;input.placeholder=placeholder;const find=button('搜索',async()=>{query=input.value;page=0;await redraw();});input.onkeydown=e=>{if(e.key==='Enter')find.click();};line.append(input,find);$('content').append(line);}
async function showOverview(){title('存档结构分析','每个数据区均保留原始 ID。下方列出存档中实际存在的结构，包括空数组。');
 if(overview.catalogue_error)$('content').append(el('p','本机配置未载入：'+overview.catalogue_error+'。填写游戏目录后重新打开可启用扩展编辑。','error'));
 else $('content').append(el('p',`本机资料：${overview.catalogue.items} 个物品 ID，${overview.catalogue.skills} 个技能，${overview.catalogue.levels} 个店铺等级。员工等级上限 N/R/SR/SSR：${overview.catalogue.maid_limits.join(' / ')}。`));
 const body=table(['数据区','条目数','存档体积','含义与编辑范围']);for(const s of overview.sections){const name=button(s.title,async()=>{tab='raw';page=0;query=s.path+'/';await render();},'secondary');row(body,[name,s.count,(s.bytes/1024).toFixed(1)+' KiB',s.help]);}
 $('content').append(el('p','员工头像保存为 _charaIconByte 字节数组，占据大部分字段数量。默认字段浏览隐藏这些字节；搜索 _charaIconByte 可单独查看。日期、昼夜、剧情、教程、地图及任务暂为只读，以保留时间和奖励关联。'));
}
async function showShop(){const d=await view('shop');overviewLevelCache=d.level_catalogue;title('店铺数据','可修改资金、H 点、名称、等级、经验、评分、难度与融资次数。时间和槽位资料保持只读。');if(d.level_info)$('content').append(el('p',`原存档等级配置：基础客流 ${d.level_info.guests}，工作员工上限 ${d.level_info.maids}，下一级所需经验 ${d.level_info.next_exp}。`));$('content').append(fieldsGrid(d.fields));const details=el('details'),t=el('table'),tbody=el('tbody');details.append(el('summary','查看完整店铺等级表'));row(tbody,['等级','升级经验','基础客流','员工上限']);for(const v of d.level_catalogue)row(tbody,[v.level,v.next_exp,v.guests,v.maids]);t.append(tbody);details.append(t);$('content').append(details);}
function staffSelector(){const line=el('div',undefined,'line'),select=el('select');for(const s of overview.staff){const o=el('option',`${s.player?'玩家':'员工'} #${s.id} · ${s.name} · Lv${s.level}`);o.value=s.id;select.append(o);}if(!overview.staff.some(s=>s.id===employeeId))employeeId=overview.staff[0]?.id||0;select.value=employeeId;select.onchange=run(async()=>{employeeId=Number(select.value);await render();});line.append(select);$('content').append(line);}
function employeeShortcuts(d){
 const target=employeeId,prefix=`/Charas/${target}/Attr/`,panel=el('div',undefined,'shortcut-panel'),line=el('div',undefined,'line');
 const route=el('select');route.setAttribute('aria-label','员工强化路线');for(const [v,n] of [['kitchen','厨房路线 · 做饭特质'],['hall','大堂路线 · 小费']]){const o=el('option',n);o.value=v;route.append(o);}route.value=employeePresetOptions.get(target)?.route||(overview.staff.find(s=>s.id===target)?.work===1?'kitchen':'hall');route.onchange=()=>employeePresetOptions.set(target,{route:route.value});
 const snapshot=paths=>Object.fromEntries(Object.entries(changes).filter(([p])=>paths.some(root=>p===root||p.startsWith(root+'/'))));
 const apply=async mode=>{validInputs();const job=session,beforeEmployee=clone(Object.fromEntries(Object.entries(changes).filter(([p])=>p.startsWith(prefix)))),result=await api('/api/employee-preset',{job,id:target,mode,route:route.value});if(session!==job||employeeId!==target||!same(beforeEmployee,Object.fromEntries(Object.entries(changes).filter(([p])=>p.startsWith(prefix)))))throw Error('目标员工或属性已改变，请重试');const paths=Object.keys(result.changes),before=snapshot(paths);for(const [p,v] of Object.entries(result.originals))remember(p,v,(d.fields.find(f=>f.path===p)?.label||'技能清单')+' · '+p);for(const [p,v] of Object.entries(result.changes))change(p,v);employeePresetHistory.push({target,paths,before,after:snapshot(paths)});if(employeePresetHistory.length>10)employeePresetHistory.shift();await render();status('员工快捷修改已暂存；点击“预览并保存”后写入存档并更新备份。');};
 panel.append(el('h3','员工路线技能优化'),el('p','快捷操作仅替换路线技能，稀有度、等级、经验及全部基础属性保持原值。请在游戏中使用知识书正常升级，以获得逐级成长。'),route,el('small','厨房：最高档料理品质、烹饪速度、魅力和 H 点技能；大堂：可叠加的小费技能，按结账/点单/送餐加成总和选择。技能数量按当前稀有度槽位上限，厨房优先品质与烹饪速度。魅力技能的加成由游戏应用，不会把基础魅力改到上限。实际工作区域保持原值。技能档位由 ID 决定，技能 Exp 为保留字段。'));
 for(const [mode,name] of [['skills','替换为路线最优技能']]){const b=button(name,async()=>{b.disabled=true;try{await apply(mode);}finally{b.disabled=false;}},'');b.disabled=!!overview.catalogue_error||overview.staff.find(s=>s.id===target)?.player;line.append(b);}
 const entry=employeePresetHistory.findLast?employeePresetHistory.findLast(v=>v.target===target):[...employeePresetHistory].reverse().find(v=>v.target===target),undo=button('撤销上次员工快捷操作',async()=>{if(!entry)return;if(!same(snapshot(entry.paths),entry.after))throw Error('快捷操作后相关属性又被修改；请先撤销这些手动修改，或使用“撤销全部修改”。');for(const p of Object.keys(snapshot(entry.paths)))delete changes[p];Object.assign(changes,clone(entry.before));employeePresetHistory.splice(employeePresetHistory.indexOf(entry),1);pending();await render();},'secondary');undo.disabled=!entry;line.append(undo);panel.append(line);$('content').append(panel);
}
async function showEmployee(){title('每位员工的属性与技能','编辑基础属性。直接改等级不会模拟随机成长；当前体力没有单独存档，载入时由最大体力初始化。');staffSelector();const generation=renderGeneration,d=await view('employee');if(generation!==renderGeneration)return;employeeShortcuts(d);$('content').append(fieldsGrid(d.fields));
 if(d.limits)$('content').append(el('p',`等级上限 N/R/SR/SSR：${d.limits.join(' / ')}；技能数上限：${d.slots.join(' / ')}。调整稀有度或等级时须让经验和技能数与最终设置一致。`));
 $('content').append(el('h3','技能'));const path=d.skills_path;remember(path,d.skills,`员工 #${employeeId} 技能清单`);const skills=appliedArray(path,d.skills),body=table(['技能名称 / ID','技能经验','效果','操作']);const saveSkills=a=>{change(path,a);return render();};
 for(const [i,s] of skills.entries()){const mst=d.skill_catalogue.find(v=>v.id===s.SkillMstID),select=el('select');for(const v of d.skill_catalogue){const o=el('option',v.name+' · '+v.id);o.value=v.id;select.append(o);}select.value=s.SkillMstID;select.disabled=!d.skill_catalogue.length;select.onchange=run(async()=>{skills[i].SkillMstID=select.value;await saveSkills(skills);});const exp=el('input');exp.type='number';exp.required=true;exp.min=0;exp.max=2147483647;exp.step=1;exp.value=s.Exp;exp.oninput=()=>{skills[i].Exp=Number(exp.value);change(path,skills);};exp.disabled=!d.skill_catalogue.length;
 const effects=(mst?.buffs||[]).map(b=>`${b.type}: ${b.value}${b.value2?' / '+b.value2:''} · ${b.description}`).join('\n');const remove=button('移除',async()=>{skills.splice(i,1);await saveSkills(skills);},'secondary');remove.disabled=!d.skill_catalogue.length;row(body,[select,exp,effects||mst?.description||'未知 ID，原样保留',remove]);}
 if(d.skill_catalogue.length){const line=el('div',undefined,'line'),select=el('select');for(const v of d.skill_catalogue){const o=el('option',v.name+' · '+v.id);o.value=v.id;select.append(o);}line.append(select,button('添加技能',async()=>{skills.push({SkillMstID:select.value,Exp:0});await saveSkills(skills);}));$('content').append(line);}
 $('content').append(el('p','技能档位由 ID 决定；Exp 是随存档保存的保留字段，当前版本未发现由它触发升级。相同 ID 不可重复，同类型的非小费技能不能叠加。载入时重新应用技能效果。'));const line=el('div',undefined,'line');for(const p of d.readonly_paths)line.append(button('查看 '+p.split('/').filter(Boolean).at(-1),async()=>{tab='raw';query=p;page=0;await render();},'secondary'));$('content').append(line);
}
async function loadInventory(){if(!inventoryData){inventoryData=await view('inventory');remember('/Items',inventoryData.array_value,'仓库清单');itemDetails={...itemDetails,...inventoryData.item_details};}}
const shopOrder=['Furniture','Clothes','GeneralShop','DarkMerchant'];
const shopFallback={Furniture:'家具店',Clothes:'服装店',GeneralShop:'杂货店',DarkMerchant:'神秘商人',other:'未列入商店目录',unknown:'未知物品'};
const typeFallback={Furniture:'家具',Clothes:'服装',UseItem:'使用道具',Gifts:'礼物',CookingBook:'料理书',Ingredients:'食材',Food:'料理'};
function sourceKeys(mst){return Array.isArray(mst.sources)?mst.sources.length?mst.sources:['other']:['unknown'];}
function shopName(key,d=inventoryData){const name=d?.shop_labels?.[key];return name&&!name.startsWith('CSShopType.')?name:shopFallback[key]||key;}
function typeName(key,d=inventoryData){const name=d?.type_labels?.[key];return name&&!name.startsWith('CSItemType.')?name:typeFallback[key]||key;}
function sourceText(mst,d=inventoryData){return sourceKeys(mst).map(k=>shopName(k,d)).join(' / ');}
function itemFilters(d,counts,types){const line=el('div',undefined,'line');const select=(label,options,current,fn)=>{const control=el('select');control.setAttribute('aria-label',label);for(const [v,n] of options){const o=el('option',n);o.value=v;control.append(o);}control.value=current;control.onchange=run(async()=>{fn(control.value);page=0;await render();});line.append(control);};select('购买来源筛选',[['','全部购买来源'],...shopOrder.concat(['other',...(counts.unknown!==undefined?['unknown']:[])]).map(k=>[k,shopName(k,d)+' · '+(counts[k]||0)+' 项'])],inventorySource,v=>inventorySource=v);select('物品类型筛选',[['','全部物品类型'],...types.map(k=>[k,typeName(k,d)])],inventoryKind,v=>inventoryKind=v);select('物品排序',[['source','按购买来源 / 名称'],['name','按名称'],['id','按原始 ID']],inventorySort,v=>inventorySort=v);$('content').append(line);}
async function showInventory(){const generation=renderGeneration;await loadInventory();if(generation!==renderGeneration)return;title('仓库与物品','修改数量、逐项移除，或从本机有效目录添加物品。数量按实际堆叠上限校验。仓库变化不会移动已摆放家具。');$('content').append(el('small','购买来源依据游戏商店目录，包含后续任务解锁的商品；不代表这件物品的实际购买记录。'));searchbar(render);const values=appliedArray('/Items',inventoryData.array_value),all=values.map((v,index)=>({v,index,mst:itemDetails[v.m]||{}})),counts=Object.fromEntries([...shopOrder,'other','unknown'].map(k=>[k,all.filter(x=>sourceKeys(x.mst).includes(k)).length])),types=[...new Set([...inventoryData.types,...all.map(x=>x.mst.type||'未知')])].sort();itemFilters(inventoryData,counts,types);const entries=all.filter(x=>(!inventorySource||sourceKeys(x.mst).includes(inventorySource))&&(!inventoryKind||(x.mst.type||'未知')===inventoryKind)&&query.toLowerCase().split(' ').every(q=>(x.v.m+' '+(x.mst.name||'')+' '+(x.mst.type||'')+' '+(x.mst.group||'')+' '+sourceText(x.mst)).toLowerCase().includes(q)));const rank=x=>{const k=sourceKeys(x.mst)[0],i=shopOrder.indexOf(k);return i<0?k==='other'?4:5:i;};entries.sort((a,b)=>inventorySort==='source'&&rank(a)!==rank(b)?rank(a)-rank(b):inventorySort==='id'?a.v.m.localeCompare(b.v.m):(a.mst.name||a.v.m).localeCompare(b.mst.name||b.v.m,'zh-CN')||a.v.m.localeCompare(b.v.m));page=Math.min(page,Math.max(0,Math.ceil(entries.length/25)-1));const body=table(['物品 / ID','购买来源','物品类型','数量 / 上限','价格','操作']);
 for(const {v,index,mst} of entries.slice(page*25,(page+1)*25)){const name=el('div',mst.name||v.m);name.append(el('small',v.m),el('small',mst.description||'未知物品；可保留原值或逐项移除。'));const count=el('input');count.type='number';count.required=true;count.min=0;count.max=mst.stack||0;count.step=1;count.value=v.c;count.disabled=!inventoryData.editable||!mst.stack;count.oninput=()=>{values[index].c=Number(count.value);change('/Items',values);};const cell=el('div');cell.append(count,el('small','本机堆叠上限：'+(mst.stack||'未知')));const remove=button('移除条目',async()=>{values.splice(index,1);change('/Items',values);await render();},'secondary');remove.disabled=!inventoryData.editable;row(body,[name,sourceText(mst),typeName(mst.type||'未知')+' / '+(mst.group||'未知'),cell,`${mst.price??'—'} / 卖出 ${mst.sell??'—'}`,remove]);}
 pager(entries.length,25,render);$('content').append(button('打开可添加物品目录',async()=>{tab='catalogue';page=0;query='';await render();}));$('content').append(el('p','料理书只要仍作为条目存在，就可能被游戏视为已持有；要移除对应菜谱来源，应移除料理书条目，而不是只将数量设为 0。食材价格记录不是库存，Ingredients 与 Food 不作为普通仓库物品添加。'));
}
async function showCatalogue(){const generation=renderGeneration;await loadInventory();if(generation!==renderGeneration)return;if(inventorySource==='unknown')inventorySource='';if(inventoryKind==='未知')inventoryKind='';title('本机物品目录','保留名称、原始 ID、分类和真实堆叠上限。禁止物品、无限物品、测试物品与家具子物件不会列为可添加。');searchbar(render);const d=await api('/api/catalogue'+base()+'&page='+page+'&q='+encodeURIComponent(query)+'&source='+encodeURIComponent(inventorySource)+'&kind='+encodeURIComponent(inventoryKind)+'&sort='+inventorySort);if(generation!==renderGeneration)return;itemFilters(d,d.source_counts,d.types);const body=table(['物品 / ID','购买来源','物品类型','堆叠上限','操作']);for(const mst of d.entries){itemDetails[mst.id]={...itemDetails[mst.id],...mst};const name=el('div',mst.name);name.append(el('small',mst.id),el('small',mst.description));const line=el('div',undefined,'line'),count=el('input');count.type='number';count.required=true;count.min=1;count.max=mst.stack;count.step=1;count.value=1;const add=button('添加 / 增加',async()=>{const n=Number(count.value);if(!Number.isInteger(n)||n<1)throw Error('数量须为正整数');const values=appliedArray('/Items',inventoryData.array_value),found=values.find(v=>v.m===mst.id),total=(found?.c||0)+n;if(total>mst.stack)throw Error('超过物品堆叠上限 '+mst.stack);if(found)found.c=total;else values.push({m:mst.id,c:n});change('/Items',values);status('已暂存 '+mst.name+' × '+n+'，可返回仓库或预览导出。');});line.append(count,add);row(body,[name,sourceText(mst,d),typeName(mst.type,d)+' / '+mst.group,mst.stack,line]);}pager(d.count,25,render);$('content').append(button('返回仓库',async()=>{tab='inventory';page=0;query='';await render();},'secondary'));}
async function showMenus(){const d=await view('menus');title('菜单份数与售价',d.help);const body=table(['菜品 / ID','所需食材 ID','剩余份数','单份售价']);for(const e of d.entries){const name=el('div',e.name);name.append(el('small',e.id));row(body,[name,e.ingredients,...e.fields.map(f=>f?fieldControl(f):el('span','缺失字段'))]);}}
async function showMap(){const d=await view('map');title('已摆放物品与房间扩建','这些数据已解析，当前为只读。家具占地、子物体、网格占用和房间解锁关联不能由改仓库数量代替。');searchbar(render);const names={Hall:'大厅',Kitchen:'厨房',MaidRoom:'休息室'};for(const [room,grids] of Object.entries(d.rooms))$('content').append(el('p',`${names[room]}已解锁网格编号：${grids.join(', ')}`));const body=table(['物品 / ID','网格坐标','朝向','类型 / 占地','魅力']);for(const e of d.entries)row(body,[e.name+' · '+e.id,`${e.x}, ${e.y}`,e.dir,`${e.type||'—'} / ${e.size||'—'}`,e.charm]);pager(d.count,25,render);}
async function showMissions(){const d=await view('missions');title('任务进度与奖励状态','id 是任务 ID，v 是当前进度，i 表示是否已领取奖励。此处只读，不操作 Steam 成就，也不重复发放任务奖励。');searchbar(render,'按任务 ID 或类型搜索');const body=table(['任务 ID / 类型','进度 / 目标','奖励已领取','资金 / H 点奖励','关联成就 ID']);for(const e of d.entries)row(body,[e.id+' / '+e.type,`${e.value} / ${e.max??'未知'}`,e.received?'是':'否',`${e.cash??'—'} / ${e.hpoint??'—'}`,e.achievement||'—']);pager(d.count,25,render);}
async function showRaw(){title('全部存档字段','按路径搜索并分页显示；可编辑字段直接显示输入框，其余保留原始值。默认隐藏头像字节。');searchbar(render,'原始路径，例如 /Charas/1/Looks/');const d=await api('/api/fields'+base()+'&page='+page+'&q='+encodeURIComponent(query)),body=table(['名称 / 原始路径','值 / 编辑','类型']);for(const f of d.rows){const name=el('div',f.label||f.path);name.append(el('small',f.path));const shown=textvalue(f.value);row(body,[name,f.rule?fieldControl(f):shown.length>500?shown.slice(0,500)+'…':shown,f.kind+(f.rule?' · 可编辑':' · 只读')]);}pager(d.count,60,render);}
let previewView=null,previewOwner='';const previewStates=new Map();let wardrobeSlotNames={};
async function render(){renderGeneration++;if(previewView){previewStates.set(previewOwner,previewView.viewState());previewView.destroy();previewView=null;}const content=$('content');content.replaceChildren();for(const b of $('tabs').querySelectorAll('button'))b.classList.toggle('active',b.dataset.tab===tab||tab==='catalogue'&&b.dataset.tab==='inventory');await {overview:showOverview,shop:showShop,employees:showEmployee,appearance:showAppearance,inventory:showInventory,catalogue:showCatalogue,menus:showMenus,map:showMap,missions:showMissions,raw:showRaw}[tab]();}
async function opened(job){status('后台解析存档和读取本机游戏配置中…');const m=await poll(job);session=job;overview=await api('/api/overview'+base());changes={};employeePresetHistory=[];employeePresetOptions.clear();baseline={};labels={};inventoryData=null;previewStates.clear();itemDetails={};inventorySource='';inventoryKind='';inventorySort='source';tab='overview';page=0;query='';$('result').replaceChildren();$('workspace').hidden=false;pending();status(`已打开 · ${overview.staff.filter(s=>!s.player).length} 名员工 + 玩家 · ${m.fields.toLocaleString()} 个原始字段 · ${(m.bytes/1048576).toFixed(1)} MiB`);await render();}
function diffRows(){const list=[];for(const [p,next] of Object.entries(changes)){const before=baseline[p];if(p==='/Items'){const old=new Map(before.map(x=>[x.m,x])),now=new Map(next.map(x=>[x.m,x]));for(const key of new Set([...old.keys(),...now.keys()]))if(!same(old.get(key),now.get(key)))list.push([`仓库 · ${itemDetails[key]?.name||key} · ${key}`,old.get(key)?.c??'未持有',now.get(key)?.c??'移除条目']);}else if(p.endsWith('/Looks/WearingClothes')){const describe=a=>a.map(v=>`${itemDetails[v.ItemMstID]?.name||v.ItemMstID} · ${v.ItemMstID} · ${v.Slots.map(s=>wardrobeSlotNames[s]||s).join(' / ')}`).join('\n')||'未穿戴';list.push([labels[p]||p,describe(before),describe(next)]);}else if(Array.isArray(next)){const describe=a=>a.map(s=>`${s.SkillMstID} (Exp ${s.Exp})`).join('\n')||'无';list.push([labels[p]||p,describe(before),describe(next)]);}else list.push([labels[p]||p,textvalue(before),textvalue(next)]);}return list;}
function validInputs(){const invalid=[...document.querySelectorAll('#content input')].find(i=>!i.checkValidity());if(invalid){invalid.reportValidity();throw Error('请修正当前页面的无效输入');}for(const [p,v] of Object.entries(changes))if(typeof v==='number'&&!Number.isFinite(v))throw Error('数值无效：'+p);}
$('review').onclick=run(async()=>{validInputs();$('diff').replaceChildren();for(const r of diffRows())row($('diff'),r);$('preview').showModal();});$('cancel').onclick=()=>{$('preview').close();};
$('confirm').onclick=run(async()=>{const snapshot=clone(changes);$('confirm').disabled=true;try{status('后台验证修改、备份并保存原存档中…');const d=await api('/api/save',{job:session,changes:snapshot}),r=await poll(d.job);$('preview').close();changes={};pending();$('result').replaceChildren(el('p','已保存：'+r.file),el('p','备份：'+r.backup));status('保存完成，正在重新读取存档…');try{await opened((await api('/api/open',{source:r.file,game:$('game').value})).job);}catch(e){status('存档已保存且已备份；重新读取失败：'+e.message);return;}$('result').replaceChildren(el('p','已保存：'+r.file),el('p','备份：'+r.backup));status('保存完成：原存档已更新，.sd.bak 为本次保存前的存档。');}finally{$('confirm').disabled=false;}});
$('reset').onclick=run(async()=>{changes={};employeePresetHistory=[];pending();await render();});for(const b of $('tabs').querySelectorAll('button'))b.onclick=run(async()=>{tab=b.dataset.tab;page=0;query='';await render();});
$('open').onclick=run(async()=>{if(!$('saves').value)throw Error('未找到存档，请选择 .sd 文件');$('open').disabled=true;try{await opened((await api('/api/open',{source:$('saves').value,game:$('game').value})).job);}finally{$('open').disabled=false;}});
$('upload').onchange=run(async()=>{const file=$('upload').files[0];if(!file)return;status('上传到本机编辑器…');const r=await fetch('/api/upload?game='+encodeURIComponent($('game').value),{method:'POST',headers:{'X-Editor-Token':token,'Content-Type':'application/octet-stream'},body:file}),d=await r.json();if(!r.ok)throw Error(d.error);await opened(d.job);});
run(async()=>{const d=await api('/api/saves');for(const s of d.saves){const o=el('option',s);o.value=s;$('saves').append(o);}status(d.saves.length?'已找到 '+d.saves.length+' 个本地存档':'未自动找到存档，请选择 .sd 文件');})();
let steamEntries=[],steamPage=0,steamBusy=false,steamSelected=null;
function steamStatus(text,error=false){$('steam-status').textContent=text;$('steam-status').className=error?'error':'';}
function steamRender(){
 const host=$('steam-list');host.replaceChildren();const q=$('steam-search').value.toLowerCase(),filter=$('steam-filter').value;
 const entries=steamEntries.filter(e=>(filter==='all'||e.unlocked===(filter==='unlocked'))&&`${e.name} ${e.id} ${e.description}`.toLowerCase().includes(q));
 const wrap=el('div',undefined,'tablewrap'),t=el('table'),head=el('thead'),r=el('tr'),body=el('tbody');for(const h of ['成就 / ID','条件说明','状态','操作'])r.append(el('th',h));head.append(r);t.append(head,body);wrap.append(t);host.append(wrap);
 for(const e of entries.slice(steamPage*25,(steamPage+1)*25)){const name=el('div',e.name||e.id);name.append(el('small',e.id));const action=button('解锁此成就',async()=>{steamSelected=e;$('steam-selected').textContent=`${e.name||e.id} · ${e.id}\n${e.description}`;$('steam-confirm').showModal();});action.disabled=steamBusy||e.unlocked;row(body,[name,e.description+(e.hidden?'（隐藏成就）':''),e.unlocked?'已解锁'+(e.time?' · '+new Date(e.time*1000).toLocaleString():''):'未解锁',action]);}
 const line=el('div',undefined,'line'),prev=button('上一页',async()=>{steamPage--;steamRender();},'secondary'),next=button('下一页',async()=>{steamPage++;steamRender();},'secondary');prev.disabled=steamPage===0;next.disabled=(steamPage+1)*25>=entries.length;line.append(prev,el('span',`${steamPage+1} / ${Math.max(1,Math.ceil(entries.length/25))} 页 · ${entries.length} 项`),next);host.append(line);
}
async function steamJob(operation,achievement){
 if(steamBusy)return;steamBusy=true;$('steam-refresh').disabled=true;$('steam-submit').disabled=true;steamRender();
 try{steamStatus(operation==='list'?'正在读取 Steam 成就…':'正在提交一个成就并等待 Steam 确认…');const d=await api('/api/steam',{operation,game:$('game').value,achievement,confirmed:operation==='unlock'}),r=await poll(d.job);
  if(operation==='list'){steamEntries=r.entries;steamPage=0;steamStatus(`Steam 已连接 · ${r.entries.filter(e=>e.unlocked).length} / ${r.entries.length} 项已解锁`);}
  else{steamEntries=steamEntries.map(e=>e.id===r.achievement.id?r.achievement:e);$('steam-confirm').close();steamStatus(r.already_unlocked?'此成就已经解锁':'Steam 已确认提交，回读显示已解锁。');}
 }catch(e){steamStatus(e.message,true);}finally{steamBusy=false;$('steam-refresh').disabled=false;$('steam-submit').disabled=false;steamRender();}
}
$('steam-refresh').onclick=()=>steamJob('list');$('steam-submit').onclick=()=>steamSelected&&steamJob('unlock',steamSelected.id);$('steam-cancel').onclick=()=>{$('steam-confirm').close();};
for(const id of ['steam-search','steam-filter'])$(id).addEventListener('input',()=>{steamPage=0;steamRender();});

async function showAppearance(){
 title('女仆捏人 · 实验版','使用本机游戏的真实模型与贴图，实时预览尺寸和配色；切换发型会后台读取对应部件。切换部件保留视角；已加载的网格和贴图会复用。当前为静止绑定姿势与近似光照。');
 const target=employeeId,select=el('select');select.setAttribute('aria-label','捏人目标女仆');for(const s of overview.staff){const o=el('option',s.name+(s.player?' · 玩家（只读）':''));o.value=s.id;select.append(o);}select.value=target;select.onchange=run(async()=>{employeeId=Number(select.value);await render();});$('content').append(select);
 const d=await view('appearance'),prefix=`/Charas/${target}/Looks/Colors/`,byKey=Object.fromEntries(d.fields.map(f=>[f.path.slice(prefix.length),f]));for(const f of d.fields)remember(f.path,f.value,f.label+' · '+f.path);remember(d.wearing_path,d.wearing_value,'女仆 #'+target+' 衣装清单');let hiddenSlots=new Set(),wardrobeBusy=false;const owner=session+':'+target;const clothingHistory=[];wardrobeSlotNames=Object.fromEntries(Object.entries(d.clothing_slots).map(([k,v])=>[k,v[1]]));for(const item of d.clothing_catalogue)itemDetails[item.id]={...itemDetails[item.id],name:item.name};
 const top=el('div',undefined,'appearance-top'),viewer=el('div',undefined,'viewer-panel'),canvas=el('canvas');canvas.id='maid-canvas';canvas.setAttribute('aria-label','女仆实时三维预览');const message=el('p','准备读取本机模型…'),views=el('div',undefined,'line');for(const [mode,name] of [['all','全身'],['upper','上半身'],['face','面部'],['back','背面']])views.append(button(name,async()=>previewView?.focus(mode),'secondary'));viewer.append(canvas,views,el('small','拖动旋转 · 滚轮缩放'),message);
 const side=el('div',undefined,'appearance-controls'),img=el('img');img.className='maid-portrait';img.alt='原存档角色头像';img.src='/api/portrait'+base()+'&id='+target;img.onerror=()=>{img.hidden=true;};const portrait=el('details');portrait.append(el('summary','原存档头像'),img,el('small','原存档头像是缓存，不随编辑重绘；游戏里的旧头像也可能暂时保留。'));side.append(portrait);
 const getValues=()=>{const result={};for(const f of d.fields){const key=f.path.slice(prefix.length),parts=key.split('/');if(parts.length===1)result[key]=value(f.path,f.value);else{result[parts[0]]??=[0,0,0,1];result[parts[0]]['rgba'.indexOf(parts[1])]=value(f.path,f.value);}}return result;};
 let busy=false,dirty=false,timer=null;const prepared=new Map();
 const configuration=()=>{const selected={};for(const key of ['HairModel','EarType','EyeTex','EyeHighLightTex','Tattoo1Tex','Tattoo2Tex'])if(byKey[key])selected[key]=value(byKey[key].path,byKey[key].value);return {selected,wearing:appliedArray(d.wearing_path,d.wearing_value),game:$('game').value};};
 const load3d=async(force=false)=>{if(!canvas.isConnected)return;if(busy){dirty=true;return;}busy=true;refresh.disabled=true;message.textContent='准备切换部件；当前模型仍可旋转…';const config=configuration(),key=JSON.stringify(config);try{let entry=force?null:prepared.get(key);if(!entry){const job=await api('/api/preview',{job:session,id:target,...config}),manifest=await poll(job.job);entry={job:job.job,manifest};prepared.set(key,entry);while(prepared.size>16)prepared.delete(prepared.keys().next().value);}else{prepared.delete(key);prepared.set(key,entry);}if(!canvas.isConnected)return;if(JSON.stringify(configuration())!==key){dirty=true;return;}if(!previewView){previewView=new MaidPreview(canvas);previewOwner=owner;previewView.restoreView(previewStates.get(owner));}const renderer=previewView;renderer.values=getValues();await renderer.load(entry.manifest,name=>'/api/preview-file?job='+entry.job+'&name='+encodeURIComponent(name),{'X-Editor-Token':token});if(!canvas.isConnected)return;renderer.setHiddenSlots(hiddenSlots);renderer.update(getValues());message.className='';message.textContent=`已载入 ${entry.manifest.parts.length} 个真实模型部件。视角保持；重复部件复用。${entry.manifest.warnings.length?' '+entry.manifest.warnings.join('；'):''}`;}catch(e){message.textContent='3D 预览：'+e.message;message.className='error';}finally{busy=false;refresh.disabled=false;if(dirty){dirty=false;load3d();}}};
 const reload=()=>{clearTimeout(timer);timer=setTimeout(()=>load3d(),250);},live=()=>previewView?.update(getValues()),refresh=button('重新读取 3D 模型',()=>load3d(true),'secondary');refresh.disabled=!d.supported;viewer.append(refresh);

 const size=byKey.BreastSize;if(size){const control=fieldControl(size),slider=el('input');slider.type='range';slider.min=0;slider.max=100;slider.step=1;slider.value=value(size.path,size.value);slider.disabled=!size.rule;slider.setAttribute('aria-label','胸部尺寸滑块');const output=el('p',`尺寸权重 ${slider.value} / 100`),numeric=control.querySelector('input');slider.oninput=()=>{change(size.path,Number(slider.value));if(numeric)numeric.value=slider.value;output.textContent=`尺寸权重 ${slider.value} / 100`;live();};if(numeric)numeric.addEventListener('input',()=>{slider.value=numeric.value;output.textContent=`尺寸权重 ${numeric.value} / 100`;live();});side.append(control,slider,output,el('small','尺寸是模型变形权重，不是罩杯或厘米。尚未找到独立胸型、脸型、身高、腰围字段。'));}top.append(viewer,side);$('content').append(top);
 if(!d.supported){$('content').append(el('p',d.reason,'error'));message.textContent=d.reason;}
 const shape=el('div',undefined,'fieldgrid');for(const key of ['HairModel','EarType','EyeTex','EyeHighLightTex','Tattoo1Tex','Tattoo2Tex']){const f=byKey[key];if(!f)continue;const wrap=fieldControl(f);if(f.rule){const selector=wrap.querySelector('select'),options=f.rule.choices,current=value(f.path,f.value);if(!options.some(o=>o.value===current)){const o=el('option','原有未知值 · '+current);o.value=current;selector.prepend(o);selector.value=current;}selector.addEventListener('change',reload);
   if(key==='HairModel'){const search=el('input'),length=el('select'),info=el('small');search.placeholder='按发型 ID 搜索';search.setAttribute('aria-label','搜索发型');for(const [v,t] of [['all','全部长度'],['short','短发'],['long','长发']]){const o=el('option',t);o.value=v;length.append(o);}length.setAttribute('aria-label','发型长度筛选');const refill=()=>{const current=value(f.path,f.value),q=search.value.toLowerCase(),hair=new Map(d.catalogue.hair.map(h=>[h.id,h])),filtered=options.filter(o=>o.value===current||(o.label.toLowerCase().includes(q)&&(length.value==='all'||hair.get(o.value)?.short===(length.value==='short'))));selector.replaceChildren();if(!filtered.some(o=>o.value===current)){const o=el('option','原有未知 ID · '+current);o.value=current;selector.append(o);}for(const o of filtered){const opt=el('option',o.label);opt.value=o.value;selector.append(opt);}selector.value=current;info.textContent=`本机 ${options.length} 种有效发型；原表使用占位名称，因此保留真实 ID。`;};search.oninput=refill;length.onchange=refill;wrap.append(search,length,info);refill();}}
  shape.append(wrap);
 }side.append(shape);
 if(d.supported){const line=el('div',undefined,'line'),source=el('select');source.setAttribute('aria-label','借用外观的来源女仆');for(const s of overview.staff.filter(s=>!s.player&&s.id!==target)){const o=el('option',s.name);o.value=s.id;source.append(o);}const borrow=async colorsOnly=>{if(!source.value)throw Error('没有其他女仆可以借用');const other=await api('/api/view'+base()+'&section=appearance&id='+source.value);if(!other.supported)throw Error('来源模型尚不支持');for(const f of other.fields){const key=f.path.split('/Colors/')[1],dest=byKey[key];if(!dest?.rule||(colorsOnly&&!key.includes('/')))continue;if(dest.rule.type==='choice'&&!dest.rule.choices.some(o=>o.value===f.value))continue;change(dest.path,f.value);}await render();};line.append(el('span','借用其他女仆'),source,button('复制配色',async()=>borrow(true),'secondary'),button('复制可编辑外观',async()=>borrow(false),'secondary'));side.append(line,button('撤销本女仆的外观修改',async()=>{for(const p of Object.keys(changes))if(p.startsWith(prefix))delete changes[p];pending();await render();},'secondary'));}
 const clothes=el('section',undefined,'wardrobe-panel');clothes.append(el('h3','衣装与配饰'),el('p','换装会同步暂存仓库变化：穿上扣一件，脱下返还一件；冲突槽位的旧衣会先返还。显隐只影响当前预览。套装按整件显隐。'));const clothingStatus=el('p'),wearTable=el('div'),controls=el('div',undefined,'line');
 const slotName=s=>d.clothing_slots[String(s)]?.[1]||String(s),slotText=slots=>slots.map(slotName).join(' / '),itemMap=new Map(d.clothing_catalogue.map(v=>[v.id,v]));
 const redrawClothes=()=>{wearTable.replaceChildren();const body=el('tbody'),t=el('table'),head=el('thead'),tr=el('tr');for(const label of ['部位','服装 / ID','预览显示','操作'])tr.append(el('th',label));head.append(tr);t.append(head,body);wearTable.append(t);for(const v of appliedArray(d.wearing_path,d.wearing_value)){const name=itemMap.get(v.ItemMstID)?.name||d.wearing.find(x=>x.id===v.ItemMstID)?.name||v.ItemMstID,show=el('input');show.type='checkbox';show.checked=!v.Slots.some(s=>hiddenSlots.has(s));show.setAttribute('aria-label','显示衣装 '+v.ItemMstID+' '+v.Slots.join(','));show.onchange=()=>{for(const slot of v.Slots)show.checked?hiddenSlots.delete(slot):hiddenSlots.add(slot);previewView?.setHiddenSlots(hiddenSlots);};const remove=button('脱下并返还仓库',()=>dress('unequip',v.ItemMstID,v.Slots),'secondary');remove.disabled=!d.supported||wardrobeBusy;row(body,[slotText(v.Slots),name+' · '+v.ItemMstID,show,remove]);}};
 const hideMode=mode=>{hiddenSlots=new Set(mode==='inner'?Object.keys(d.clothing_slots).map(Number).filter(s=>![3,4].includes(s)):mode==='outer'?[1,2]:[]);previewView?.setHiddenSlots(hiddenSlots);redrawClothes();};const undoDress=button('撤销上次换装',async()=>{if(wardrobeBusy||!clothingHistory.length)return;const last=clothingHistory.at(-1);if(!same(appliedArray(d.wearing_path,d.wearing_value),last.afterWear)||!same(appliedArray('/Items',inventoryData.array_value),last.afterItems))throw Error('仓库或衣装已有其他修改，不能单独回退；可使用撤销全部修改。');clothingHistory.pop();change(d.wearing_path,last.beforeWear);change('/Items',last.beforeItems);undoDress.disabled=!clothingHistory.length;stockInfo();redrawClothes();reload();clothingStatus.textContent='已撤销上次换装和对应仓库转移。';},'secondary');undoDress.disabled=true;controls.append(undoDress,button('显示全部',()=>hideMode('all'),'secondary'),button('隐藏外衣',()=>hideMode('outer'),'secondary'),button('仅看内衣',()=>hideMode('inner'),'secondary'));clothes.append(controls,wearTable);
 const search=el('input'),category=el('select'),pick=el('select'),placement=el('select'),source=el('select'),stock=el('small');search.placeholder='按服装名称或 ID 搜索';search.setAttribute('aria-label','搜索服装');category.setAttribute('aria-label','衣装部位筛选');pick.setAttribute('aria-label','选择服装');pick.size=8;placement.setAttribute('aria-label','穿戴槽位');source.setAttribute('aria-label','衣装来源');for(const [v,label] of [['all','全部部位'],...Object.entries(d.clothing_slots).map(([v,a])=>[v,a[1]])]){const o=el('option',label);o.value=v;category.append(o);}for(const [v,label] of [['inventory','从仓库穿上'],['new','新增一件并穿上']]){const o=el('option',label);o.value=v;source.append(o);}
 const stockInfo=()=>{const item=itemMap.get(pick.value);placement.replaceChildren();if(item)for(const slots of item.slots){const o=el('option',slotText(slots));o.value=JSON.stringify(slots);placement.append(o);}if(category.value!=='all'){const found=item?.slots.find(a=>a.includes(Number(category.value)));if(found)placement.value=JSON.stringify(found);}const inventory=inventoryData?appliedArray('/Items',inventoryData.array_value):[];stock.textContent='仓库现有：'+(inventory.find(v=>v.m===pick.value)?.c||0)+' 件';};
 const refill=()=>{const current=pick.value,q=search.value.toLowerCase(),matches=d.clothing_catalogue.filter(v=>(v.name+' '+v.id).toLowerCase().includes(q)&&(category.value==='all'||v.slots.some(a=>a.includes(Number(category.value)))));pick.replaceChildren();for(const v of matches){const o=el('option',v.name+' · '+v.id+' · '+v.slots.map(slotText).join(' 或 '));o.value=v.id;pick.append(o);}if(matches.some(v=>v.id===current))pick.value=current;stockInfo();};search.oninput=refill;category.onchange=refill;pick.onchange=stockInfo;
 const wearButton=button('穿上 / 替换冲突衣装',()=>{if(!pick.value)throw Error('请先选择服装');return dress('equip',pick.value,JSON.parse(placement.value),source.value);});wearButton.disabled=!d.supported;
 const dress=async(operation,item,slots,mode='inventory')=>{if(wardrobeBusy)return;wardrobeBusy=true;wearButton.disabled=true;redrawClothes();try{validInputs();await loadInventory();const requestJob=session,beforeWear=appliedArray(d.wearing_path,d.wearing_value),beforeItems=appliedArray('/Items',inventoryData.array_value);const result=await api('/api/wardrobe',{job:requestJob,id:target,operation,item,slots,mode,wearing:beforeWear,items:beforeItems});if(session!==requestJob||!same(beforeWear,appliedArray(d.wearing_path,d.wearing_value))||!same(beforeItems,appliedArray('/Items',inventoryData.array_value)))throw Error('衣装或仓库在换装过程中已改变，请重试');clothingHistory.push({beforeWear,beforeItems,afterWear:result.wearing,afterItems:result.items});if(clothingHistory.length>10)clothingHistory.shift();undoDress.disabled=false;change(d.wearing_path,result.wearing);change('/Items',result.items);clothingStatus.className='';clothingStatus.textContent='已暂存衣装和仓库变化；点击“预览并保存”才会写入存档。';stockInfo();reload();}catch(e){clothingStatus.textContent=e.message;clothingStatus.className='error';}finally{wardrobeBusy=false;wearButton.disabled=!d.supported;redrawClothes();}};
 const chooser=el('div',undefined,'wardrobe-chooser');chooser.append(search,category,pick,placement,source,stock,wearButton);clothes.append(chooser,clothingStatus);side.append(clothes);redrawClothes();refill();if(d.supported)loadInventory().then(stockInfo).catch(e=>{clothingStatus.textContent=e.message;});
 for(const [group,entries] of Object.entries(d.groups)){const details=el('details');details.open=['主发色','肤色','眼睛与眉睫'].includes(group);details.append(el('summary',group));const grid=el('div',undefined,'colorgrid');for(const [key,label] of Object.entries(entries)){const fs=['r','g','b','a'].map(c=>byKey[key+'/'+c]);if(fs.some(f=>!f))continue;const card=el('div',undefined,'color-card'),swatch=el('div',undefined,'color-swatch'),picker=el('input'),alpha=el('input'),out=el('small');picker.type='color';picker.setAttribute('aria-label',group+' '+label+'颜色');alpha.type='range';alpha.min=0;alpha.max=1;alpha.step=0.01;alpha.setAttribute('aria-label',group+' '+label+'透明度');picker.disabled=alpha.disabled=fs.some(f=>!f.rule);const raw=el('details');raw.append(el('summary','精确 RGBA 通道'));const controls=fieldsGrid(fs);raw.append(controls);const update=(sync=false)=>{const rgba=fs.map(f=>value(f.path,f.value)),rgb=rgba.slice(0,3).map(v=>Math.round(Math.max(0,Math.min(1,v))*255));picker.value='#'+rgb.map(v=>v.toString(16).padStart(2,'0')).join('');alpha.value=rgba[3];swatch.style.backgroundColor=`rgba(${rgb.join(',')},${rgba[3]})`;out.textContent=`${picker.value.toUpperCase()} · A ${displayNumber(rgba[3])}`;if(sync)for(const f of fs){const i=controls.querySelector(`input[data-path="${f.path}"]`);if(i)i.value=displayNumber(value(f.path,f.value));}};picker.oninput=()=>{const rgb=picker.value.match(/\w\w/g).map(x=>parseInt(x,16)/255);for(let c=0;c<3;c++)change(fs[c].path,rgb[c]);update(true);live();};alpha.oninput=()=>{change(fs[3].path,Number(alpha.value));update(true);live();};controls.addEventListener('input',()=>{update(false);live();});card.append(el('strong',label),swatch,picker,el('small','透明度 / Alpha'),alpha,out,raw);update();grid.append(card);}details.append(grid);side.append(details);}

 if(d.supported)load3d();
}
