'use strict';
const $=id=>document.getElementById(id),token=document.querySelector('meta[name="editor-token"]').content;
let session='',overview=null,tab='overview',employeeId=1,page=0,query='',changes={},baseline={},labels={},inventoryData=null,itemDetails={},overviewLevelCache=[];
const clone=x=>JSON.parse(JSON.stringify(x)),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function button(text,fn,cls=''){const e=el('button',text,cls);e.onclick=run(fn);return e;}
function run(fn){return async()=>{try{await fn();}catch(e){status(e.message,true);}};}
function status(s,error=false){$('status').textContent=s;$('status').className=error?'error':'';}
async function api(path,data){const r=await fetch(path,{method:data===undefined?'GET':'POST',headers:{'X-Editor-Token':token,'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d;}
async function poll(job){for(;;){const s=await api('/api/status?job='+job);if(s.state==='done')return s.result;if(s.state==='error')throw Error(s.error);await new Promise(r=>setTimeout(r,600));}}
const base=()=>'?job='+session;
async function view(section){return api('/api/view'+base()+'&section='+section+'&id='+employeeId+'&page='+page+'&q='+encodeURIComponent(query));}
function remember(path,v,label=path){if(!(path in baseline))baseline[path]=clone(v);labels[path]=label;}
function value(path,original){return path in changes?changes[path]:original;}
function pending(){const n=Object.keys(changes).length;$('pending').textContent=n?`已暂存 ${n} 项修改`:'尚无修改';$('review').disabled=!n;}
function change(path,next){
 const m=path.match(/^(\/Items|\/Charas\/\d+\/Attr\/SkillSDatas)\/(\d+)\/(\w+)$/);
 if(m&&m[1] in changes){const a=clone(changes[m[1]]);a[Number(m[2])][m[3]]=next;return change(m[1],a);}
 if(same(baseline[path],next))delete changes[path];else changes[path]=clone(next);
 if(Array.isArray(next))for(const key of Object.keys(changes))if(key.startsWith(path+'/'))delete changes[key];
 pending();
}
function appliedArray(path,original){const a=clone(value(path,original));for(const [p,v] of Object.entries(changes)){const s=p.startsWith(path+'/')?p.slice(path.length+1).split('/'):[];if(s.length===2&&a[Number(s[0])])a[Number(s[0])][s[1]]=v;}return a;}
function textvalue(v){return typeof v==='string'?v:JSON.stringify(v);}
function fieldControl(f){
 const parent=f.path.match(/^(\/Items|\/Charas\/\d+\/Attr\/SkillSDatas)\//);
 if(parent&&parent[1] in changes)f={...f,rule:null};
 remember(f.path,f.value,f.label+' · '+f.path);const wrap=el('label',undefined,'field');wrap.append(el('span',f.label),el('small',f.path));
 if(!f.rule){wrap.append(el('div',textvalue(f.value),'readonly'));return wrap;}
 const spec=f.rule;let input;
 if(spec.choices){input=el('select');for(const o of spec.choices){const opt=el('option',o.label);opt.value=String(o.value);input.append(opt);}input.value=String(value(f.path,f.value));}
 else{input=el('input');input.type=spec.type==='string'?'text':'number';input.value=value(f.path,f.value);if(input.type==='number'){input.required=true;input.min=spec.min;input.max=spec.max;input.step=spec.type==='integer'?'1':'any';}else input.maxLength=spec.max;}
 input.dataset.path=f.path;input.setAttribute('aria-label',f.label);
 input.addEventListener(spec.choices?'change':'input',()=>{const v=spec.type==='string'||spec.type==='choice'?input.value:Number(input.value);change(f.path,v);if(f.path==='/ShopLevel'){const exp=document.querySelector('input[data-path="/ShopExp"]'),lv=overviewLevelCache.find(x=>x.level===v);if(exp&&lv)exp.max=Math.max(0,lv.next_exp-1);}wrap.classList.toggle('changed',f.path in changes);});
 wrap.classList.toggle('changed',f.path in changes);wrap.append(input);if(spec.help)wrap.append(el('small',spec.help));return wrap;
}
function fieldsGrid(fields){const grid=el('div',undefined,'fieldgrid');for(const f of fields)if(f)grid.append(fieldControl(f));return grid;}
function title(text,help){$('content').append(el('h2',text));if(help)$('content').append(el('p',help));}
function table(headers){const wrap=el('div',undefined,'tablewrap'),t=el('table'),head=el('thead'),tr=el('tr'),body=el('tbody');for(const h of headers)tr.append(el('th',h));head.append(tr);t.append(head,body);wrap.append(t);$('content').append(wrap);return body;}
function row(body,values){const tr=el('tr');for(const v of values){const td=el('td');if(v instanceof Node)td.append(v);else td.textContent=v==null?'—':String(v);tr.append(td);}body.append(tr);}
function pager(count,size,redraw){const line=el('div',undefined,'line'),prev=button('上一页',async()=>{page--;await redraw();},'secondary'),next=button('下一页',async()=>{page++;await redraw();},'secondary');prev.disabled=page===0;next.disabled=(page+1)*size>=count;line.append(prev,el('span',`第 ${page+1} / ${Math.max(1,Math.ceil(count/size))} 页 · ${count} 项`),next);$('content').append(line);}
function searchbar(redraw,placeholder='按中文名称或 ID 搜索'){const line=el('div',undefined,'line'),input=el('input');input.value=query;input.placeholder=placeholder;const find=button('搜索',async()=>{query=input.value;page=0;await redraw();});input.onkeydown=e=>{if(e.key==='Enter')find.click();};line.append(input,find);$('content').append(line);}
async function showOverview(){title('存档结构分析','每个数据区均保留原始 ID。下方列出存档中实际存在的结构，包括空数组。');
 if(overview.catalogue_error)$('content').append(el('p','本机配置未载入：'+overview.catalogue_error+'。填写游戏目录后重新打开可启用扩展编辑。','error'));
 else $('content').append(el('p',`本机资料：${overview.catalogue.items} 个物品 ID，${overview.catalogue.skills} 个技能，${overview.catalogue.levels} 个店铺等级。员工等级上限 N/R/SR/SSR：${overview.catalogue.maid_limits.join(' / ')}。`));
 const body=table(['数据区','条目数','存档体积','含义与编辑范围']);for(const s of overview.sections){const name=button(s.title,async()=>{tab='raw';page=0;query=s.path+'/';await render();},'secondary');row(body,[name,s.count,(s.bytes/1024).toFixed(1)+' KiB',s.help]);}
 $('content').append(el('p','员工头像保存为 _charaIconByte 字节数组，占据大部分字段数量。默认字段浏览隐藏这些字节；搜索 _charaIconByte 可单独查看。日期、昼夜、剧情、教程、地图及任务暂为只读，以保留时间和奖励关联。'));
}
async function showShop(){const d=await view('shop');overviewLevelCache=d.level_catalogue;title('店铺数据','可修改资金、H 点、名称、等级、经验、评分、难度与融资次数。时间和槽位资料保持只读。');if(d.level_info)$('content').append(el('p',`原存档等级配置：基础客流 ${d.level_info.guests}，工作员工上限 ${d.level_info.maids}，下一级所需经验 ${d.level_info.next_exp}。`));$('content').append(fieldsGrid(d.fields));const details=el('details'),t=el('table'),tbody=el('tbody');details.append(el('summary','查看完整店铺等级表'));row(tbody,['等级','升级经验','基础客流','员工上限']);for(const v of d.level_catalogue)row(tbody,[v.level,v.next_exp,v.guests,v.maids]);t.append(tbody);details.append(t);$('content').append(details);}
function staffSelector(){const line=el('div',undefined,'line'),select=el('select');for(const s of overview.staff){const o=el('option',`${s.player?'玩家':'员工'} #${s.id} · ${s.name} · Lv${s.level}`);o.value=s.id;select.append(o);}if(!overview.staff.some(s=>s.id===employeeId))employeeId=overview.staff[0]?.id||0;select.value=employeeId;select.onchange=run(async()=>{employeeId=Number(select.value);await render();});line.append(select);$('content').append(line);}
async function showEmployee(){title('每位员工的属性与技能','编辑基础属性。直接改等级不会模拟随机成长；当前体力没有单独存档，载入时由最大体力初始化。');staffSelector();const d=await view('employee');$('content').append(fieldsGrid(d.fields));
 if(d.limits)$('content').append(el('p',`等级上限 N/R/SR/SSR：${d.limits.join(' / ')}；技能数上限：${d.slots.join(' / ')}。调整稀有度或等级时须让经验和技能数与最终设置一致。`));
 $('content').append(el('h3','技能'));const path=d.skills_path;remember(path,d.skills,`员工 #${employeeId} 技能清单`);const skills=appliedArray(path,d.skills),body=table(['技能名称 / ID','技能经验','效果','操作']);const saveSkills=a=>{change(path,a);return render();};
 for(const [i,s] of skills.entries()){const mst=d.skill_catalogue.find(v=>v.id===s.SkillMstID),select=el('select');for(const v of d.skill_catalogue){const o=el('option',v.name+' · '+v.id);o.value=v.id;select.append(o);}select.value=s.SkillMstID;select.disabled=!d.skill_catalogue.length;select.onchange=run(async()=>{skills[i].SkillMstID=select.value;await saveSkills(skills);});const exp=el('input');exp.type='number';exp.required=true;exp.min=0;exp.max=2147483647;exp.step=1;exp.value=s.Exp;exp.oninput=()=>{skills[i].Exp=Number(exp.value);change(path,skills);};exp.disabled=!d.skill_catalogue.length;
 const effects=(mst?.buffs||[]).map(b=>`${b.type}: ${b.value}${b.value2?' / '+b.value2:''} · ${b.description}`).join('\n');const remove=button('移除',async()=>{skills.splice(i,1);await saveSkills(skills);},'secondary');remove.disabled=!d.skill_catalogue.length;row(body,[select,exp,effects||mst?.description||'未知 ID，原样保留',remove]);}
 if(d.skill_catalogue.length){const line=el('div',undefined,'line'),select=el('select');for(const v of d.skill_catalogue){const o=el('option',v.name+' · '+v.id);o.value=v.id;select.append(o);}line.append(select,button('添加技能',async()=>{skills.push({SkillMstID:select.value,Exp:0});await saveSkills(skills);}));$('content').append(line);}
 $('content').append(el('p','技能档位由 ID 决定；Exp 是随存档保存的保留字段，当前版本未发现由它触发升级。相同 ID 不可重复，同类型的非小费技能不能叠加。载入时重新应用技能效果。'));const line=el('div',undefined,'line');for(const p of d.readonly_paths)line.append(button('查看 '+p.split('/').filter(Boolean).at(-1),async()=>{tab='raw';query=p;page=0;await render();},'secondary'));$('content').append(line);
}
async function loadInventory(){if(!inventoryData){inventoryData=await view('inventory');remember('/Items',inventoryData.array_value,'仓库清单');itemDetails={...itemDetails,...inventoryData.item_details};}}
async function showInventory(){await loadInventory();title('仓库与物品','修改数量、逐项移除，或从本机有效目录添加物品。数量按实际堆叠上限校验。仓库变化不会移动已摆放家具。');searchbar(render);const values=appliedArray('/Items',inventoryData.array_value),entries=values.map((v,index)=>({v,index,mst:itemDetails[v.m]||{}})).filter(x=>query.toLowerCase().split(' ').every(q=>(x.v.m+' '+(x.mst.name||'')+' '+(x.mst.type||'')+' '+(x.mst.group||'')).toLowerCase().includes(q)));const body=table(['物品 / ID','分类','数量 / 上限','价格','操作']);
 for(const {v,index,mst} of entries.slice(page*25,(page+1)*25)){const name=el('div',mst.name||v.m);name.append(el('small',v.m),el('small',mst.description||'未知物品；可保留原值或逐项移除。'));const count=el('input');count.type='number';count.required=true;count.min=0;count.max=mst.stack||0;count.step=1;count.value=v.c;count.disabled=!inventoryData.editable||!mst.stack;count.oninput=()=>{values[index].c=Number(count.value);change('/Items',values);};const cell=el('div');cell.append(count,el('small','本机堆叠上限：'+(mst.stack||'未知')));const remove=button('移除条目',async()=>{values.splice(index,1);change('/Items',values);await render();},'secondary');remove.disabled=!inventoryData.editable;row(body,[name,(mst.type||'未知')+' / '+(mst.group||'未知'),cell,`${mst.price??'—'} / 卖出 ${mst.sell??'—'}`,remove]);}
 pager(entries.length,25,render);$('content').append(button('打开可添加物品目录',async()=>{tab='catalogue';page=0;query='';await render();}));$('content').append(el('p','料理书只要仍作为条目存在，就可能被游戏视为已持有；要移除对应菜谱来源，应移除料理书条目，而不是只将数量设为 0。食材价格记录不是库存，Ingredients 与 Food 不作为普通仓库物品添加。'));
}
async function showCatalogue(){await loadInventory();title('本机物品目录','保留名称、原始 ID、分类和真实堆叠上限。禁止物品、无限物品、测试物品与家具子物件不会列为可添加。');searchbar(render);const d=await api('/api/catalogue'+base()+'&page='+page+'&q='+encodeURIComponent(query)),body=table(['物品 / ID','分类','堆叠上限','操作']);for(const mst of d.entries){itemDetails[mst.id]={...itemDetails[mst.id],...mst};const name=el('div',mst.name);name.append(el('small',mst.id),el('small',mst.description));const line=el('div',undefined,'line'),count=el('input');count.type='number';count.required=true;count.min=1;count.max=mst.stack;count.step=1;count.value=1;const add=button('添加 / 增加',async()=>{const n=Number(count.value);if(!Number.isInteger(n)||n<1)throw Error('数量须为正整数');const values=appliedArray('/Items',inventoryData.array_value),found=values.find(v=>v.m===mst.id),total=(found?.c||0)+n;if(total>mst.stack)throw Error('超过物品堆叠上限 '+mst.stack);if(found)found.c=total;else values.push({m:mst.id,c:n});change('/Items',values);status('已暂存 '+mst.name+' × '+n+'，可返回仓库或预览导出。');});line.append(count,add);row(body,[name,mst.type+' / '+mst.group,mst.stack,line]);}pager(d.count,25,render);$('content').append(button('返回仓库',async()=>{tab='inventory';page=0;query='';await render();},'secondary'));}
async function showMenus(){const d=await view('menus');title('菜单份数与售价',d.help);const body=table(['菜品 / ID','所需食材 ID','剩余份数','单份售价']);for(const e of d.entries){const name=el('div',e.name);name.append(el('small',e.id));row(body,[name,e.ingredients,...e.fields.map(f=>f?fieldControl(f):el('span','缺失字段'))]);}}
async function showMap(){const d=await view('map');title('已摆放物品与房间扩建','这些数据已解析，当前为只读。家具占地、子物体、网格占用和房间解锁关联不能由改仓库数量代替。');searchbar(render);const names={Hall:'大厅',Kitchen:'厨房',MaidRoom:'休息室'};for(const [room,grids] of Object.entries(d.rooms))$('content').append(el('p',`${names[room]}已解锁网格编号：${grids.join(', ')}`));const body=table(['物品 / ID','网格坐标','朝向','类型 / 占地','魅力']);for(const e of d.entries)row(body,[e.name+' · '+e.id,`${e.x}, ${e.y}`,e.dir,`${e.type||'—'} / ${e.size||'—'}`,e.charm]);pager(d.count,25,render);}
async function showMissions(){const d=await view('missions');title('任务进度与奖励状态','id 是任务 ID，v 是当前进度，i 表示是否已领取奖励。此处只读，不操作 Steam 成就，也不重复发放任务奖励。');searchbar(render,'按任务 ID 或类型搜索');const body=table(['任务 ID / 类型','进度 / 目标','奖励已领取','资金 / H 点奖励','关联成就 ID']);for(const e of d.entries)row(body,[e.id+' / '+e.type,`${e.value} / ${e.max??'未知'}`,e.received?'是':'否',`${e.cash??'—'} / ${e.hpoint??'—'}`,e.achievement||'—']);pager(d.count,25,render);}
async function showRaw(){title('全部存档字段','按路径搜索并分页显示；可编辑字段直接显示输入框，其余保留原始值。默认隐藏头像字节。');searchbar(render,'原始路径，例如 /Charas/1/Looks/');const d=await api('/api/fields'+base()+'&page='+page+'&q='+encodeURIComponent(query)),body=table(['名称 / 原始路径','值 / 编辑','类型']);for(const f of d.rows){const name=el('div',f.label||f.path);name.append(el('small',f.path));const shown=textvalue(f.value);row(body,[name,f.rule?fieldControl(f):shown.length>500?shown.slice(0,500)+'…':shown,f.kind+(f.rule?' · 可编辑':' · 只读')]);}pager(d.count,60,render);}
async function render(){const content=$('content');content.replaceChildren();for(const b of $('tabs').querySelectorAll('button'))b.classList.toggle('active',b.dataset.tab===tab||tab==='catalogue'&&b.dataset.tab==='inventory');await {overview:showOverview,shop:showShop,employees:showEmployee,inventory:showInventory,catalogue:showCatalogue,menus:showMenus,map:showMap,missions:showMissions,raw:showRaw}[tab]();}
async function opened(job){status('后台解析存档和读取本机游戏配置中…');const m=await poll(job);session=job;overview=await api('/api/overview'+base());changes={};baseline={};labels={};inventoryData=null;itemDetails={};tab='overview';page=0;query='';$('result').replaceChildren();$('workspace').hidden=false;pending();status(`已打开 · ${overview.staff.filter(s=>!s.player).length} 名员工 + 玩家 · ${m.fields.toLocaleString()} 个原始字段 · ${(m.bytes/1048576).toFixed(1)} MiB`);await render();}
function diffRows(){const list=[];for(const [p,next] of Object.entries(changes)){const before=baseline[p];if(p==='/Items'){const old=new Map(before.map(x=>[x.m,x])),now=new Map(next.map(x=>[x.m,x]));for(const key of new Set([...old.keys(),...now.keys()]))if(!same(old.get(key),now.get(key)))list.push([`仓库 · ${itemDetails[key]?.name||key} · ${key}`,old.get(key)?.c??'未持有',now.get(key)?.c??'移除条目']);}else if(Array.isArray(next)){const describe=a=>a.map(s=>`${s.SkillMstID} (Exp ${s.Exp})`).join('\n')||'无';list.push([labels[p]||p,describe(before),describe(next)]);}else list.push([labels[p]||p,textvalue(before),textvalue(next)]);}return list;}
function validInputs(){const invalid=[...document.querySelectorAll('#content input')].find(i=>!i.checkValidity());if(invalid){invalid.reportValidity();throw Error('请修正当前页面的无效输入');}for(const [p,v] of Object.entries(changes))if(typeof v==='number'&&!Number.isFinite(v))throw Error('数值无效：'+p);}
$('review').onclick=run(async()=>{validInputs();$('diff').replaceChildren();for(const r of diffRows())row($('diff'),r);$('preview').showModal();});$('cancel').onclick=()=>{$('preview').close();};
$('confirm').onclick=run(async()=>{const snapshot=clone(changes);$('confirm').disabled=true;try{status('后台检查关联、导出与回读校验中…');const d=await api('/api/export',{job:session,changes:snapshot}),r=await poll(d.job);$('preview').close();$('result').replaceChildren(el('p','已导出：'+r.file),button('另存导出文件',async()=>{const a=el('a');a.href='/api/download?job='+d.job;a.download='CoffeeShop_edited.sd';a.click();}));status('导出完成：字段、关联、完整 JSON 与 GZip 回读均通过。');}finally{$('confirm').disabled=false;}});
$('reset').onclick=run(async()=>{changes={};pending();await render();});for(const b of $('tabs').querySelectorAll('button'))b.onclick=run(async()=>{tab=b.dataset.tab;page=0;query='';await render();});
$('open').onclick=run(async()=>{if(!$('saves').value)throw Error('未找到存档，请选择 .sd 文件');$('open').disabled=true;try{await opened((await api('/api/open',{source:$('saves').value,game:$('game').value})).job);}finally{$('open').disabled=false;}});
$('upload').onchange=run(async()=>{const file=$('upload').files[0];if(!file)return;status('上传到本机编辑器…');const r=await fetch('/api/upload?game='+encodeURIComponent($('game').value),{method:'POST',headers:{'X-Editor-Token':token,'Content-Type':'application/octet-stream'},body:file}),d=await r.json();if(!r.ok)throw Error(d.error);await opened(d.job);});
run(async()=>{const d=await api('/api/saves');for(const s of d.saves){const o=el('option',s);o.value=s;$('saves').append(o);}status(d.saves.length?'已找到 '+d.saves.length+' 个本地存档':'未自动找到存档，请选择 .sd 文件');})();
let steamEntries=[],steamPage=0,steamBusy=false,steamSelected=null;
function steamStatus(text,error=false){$('steam-status').textContent=text;$('steam-status').className=error?'error':'';}
function steamRender(){
 const host=$('steam-list');host.replaceChildren();const q=$('steam-search').value.toLowerCase(),filter=$('steam-filter').value;
 const entries=steamEntries.filter(e=>(filter==='all'||e.unlocked===(filter==='unlocked'))&&`${e.name} ${e.id} ${e.description}`.toLowerCase().includes(q));
 const wrap=el('div',undefined,'tablewrap'),t=el('table'),head=el('thead'),r=el('tr'),body=el('tbody');for(const h of ['成就 / ID','条件说明','状态','操作'])r.append(el('th',h));head.append(r);t.append(head,body);wrap.append(t);host.append(wrap);
 for(const e of entries.slice(steamPage*25,(steamPage+1)*25)){const name=el('div',e.name||e.id);name.append(el('small',e.id));const action=button('解锁此成就',async()=>{steamSelected=e;$('steam-selected').textContent=`${e.name||e.id} · ${e.id}\n${e.description}`;$('steam-confirm').showModal();});action.disabled=steamBusy||e.unlocked;row(body,[name,e.description+(e.hidden?'（隐藏成就）':''),e.unlocked?'已解锁'+(e.time?' · '+new Date(e.time*1000).toLocaleString():''):'未解锁',action]);}
 const line=el('div',undefined,'line'),prev=button('上一页',async()=>{steamPage--;steamRender();},'secondary'),next=button('下一页',async()=>{steamPage++;steamRender();},'secondary');prev.disabled=steamPage===0;next.disabled=(steamPage+1)*25>=entries.length;line.append(prev,el('span',`${steamPage+1} / ${Math.max(1,Math.ceil(entries.length/25))} 页 · ${entries.length} 项`),next);host.append(line);
}
async function steamJob(operation,achievement){
 if(steamBusy)return;steamBusy=true;$('steam-refresh').disabled=true;$('steam-submit').disabled=true;steamRender();
 try{steamStatus(operation==='list'?'正在读取 Steam 成就…':'正在提交一个成就并等待 Steam 确认…');const d=await api('/api/steam',{operation,game:$('game').value,achievement,confirmed:operation==='unlock'}),r=await poll(d.job);
  if(operation==='list'){steamEntries=r.entries;steamPage=0;steamStatus(`Steam 已连接 · ${r.entries.filter(e=>e.unlocked).length} / ${r.entries.length} 项已解锁`);}
  else{steamEntries=steamEntries.map(e=>e.id===r.achievement.id?r.achievement:e);$('steam-confirm').close();steamStatus(r.already_unlocked?'此成就已经解锁':'Steam 已确认提交，回读显示已解锁。');}
 }catch(e){steamStatus(e.message,true);}finally{steamBusy=false;$('steam-refresh').disabled=false;$('steam-submit').disabled=false;steamRender();}
}
$('steam-refresh').onclick=()=>steamJob('list');$('steam-submit').onclick=()=>steamSelected&&steamJob('unlock',steamSelected.id);$('steam-cancel').onclick=()=>{$('steam-confirm').close();};
for(const id of ['steam-search','steam-filter'])$(id).addEventListener('input',()=>{steamPage=0;steamRender();});
